from dydx3.constants import API_HOST_GOERLI, API_HOST_MAINNET
from decouple import  config

# !!!! SELECET MODE !!!!
MODE = "DEVELOPMENT"


# CLose all open positions and orders

ABORT_ALL_POSITIONS = True  


# Find cointegrated pairs

FIND_COINTEGRATED = True

#Place Trades
PLACE_TRADES = True

# RESOLUTION


RESOLUTION = "1HOUR"


# sTATS WIndow
WINDOW = 21


# THresholds - Opneing

MAX_HALF_LIFE = 24 
ZSCORE_THRESH = 1.5
USD_PER_TRADE = 50
USD_MIN_COLLATERAL = 1880

# THRESHOLDS - CLosing
CLOSE_AT_ZSCORE_CROSS = True

# Ethereum Address
#ETHEREUM_ADDRESS = "0x838C3A2238b448a71a2A7aD62Dc205FaBB594447" 
ETHEREUM_ADDRESS = "0x6078f7C68077c70bcD670648b74e347962b5f089"
# KEYS - Production
# Must to be on Mainnet in DYDX
STARK_PRIVATE_KEY_MAINNET = config("STARK_PRIVATE_KEY_MAINNET")
DYDX_API_KEY_MAINNET = config("DYDX_API_KEY_MAINNET")
DYDX_API_SECRET_MAINNET= config("DYDX_API_SECRET_MAINNET")
DYDX_API_PASSPHRASE_MAINNET = config("DYDX_API_PASSPHRASE_MAINNET")

# KEYS - Development
# Must to be on Testnet in DYDX
STARK_PRIVATE_KEY_TESTNET = config("STARK_PRIVATE_KEY_TESTNET")
DYDX_API_KEY_TESTNET = config("DYDX_API_KEY_TESTNET")
DYDX_API_SECRET_TESTNET = config("DYDX_API_SECRET_TESTNET")
DYDX_API_PASSPHRASE_TESTNET = config("DYDX_API_PASSPHRASE_TESTNET")

# KEYS - Export

STARK_PRIVATE_KEY = STARK_PRIVATE_KEY_MAINNET if MODE == "PRODUCTION" else STARK_PRIVATE_KEY_TESTNET
DYDX_API_KEY = DYDX_API_KEY_MAINNET if MODE == "PRODUCTION" else DYDX_API_KEY_TESTNET
DYDX_API_SECRET = DYDX_API_SECRET_MAINNET if MODE == "PRODUCTION" else DYDX_API_SECRET_TESTNET
DYDX_API_PASSPHRASE = DYDX_API_PASSPHRASE_MAINNET if MODE == "PRODUCTION" else DYDX_API_PASSPHRASE_TESTNET

# HOST - Export

HOST = API_HOST_MAINNET if MODE == "PRODUCTION" else API_HOST_GOERLI

# HTTP PROVIDER

HTTP_PROVIDER_MAINNET = "https://eth-mainnet.g.alchemy.com/v2/knu51xloBElDrFB1E4ljxCSZ-Y-fHWcZ"
HTTP_PROVIDER_TESTNET = "https://eth-goerli.g.alchemy.com/v2/ew6AOS0khjFHiEBfiV8-gKCYrEfncEI3"
HTTP_PROVIDER = HTTP_PROVIDER_MAINNET if MODE == "PRODUCTION" else HTTP_PROVIDER_TESTNET